### ISSUE TITLE
Serving on localhost

### ISSUE THREAD

**Issue by wzh1895** [forrest79/static-nginx-gallery#6]
Hi,

Thank you for creating this project!

I have been trying to run this server on my NAS but had no success. Having tried the following configurations I still see everytime the nginx default welcome page.

Configurations include: 
1. serverName: gallery.test, null, _, localhost, 192.168.xxx.xxx (my NAS IP)
2. path: null, gallery
3. port: null, xxxx (a randomly chosen port and ufw is inactive)

Whatever combination of the above 3 parameters I use to run the bin/build command (with success) and after reloading nginx I still cannot access the gallery through serverName:port/path.

Would be great to have some pointer from you :)

Thanks

**Comment by forrest79** [comment]
Hi, I would like to help you with NAS setup, but it mostly depends, how is nginx on your NAS system configured. Build process in StaticNginxGallery only prepares the configuration file and you must enable it in your system configuration. I know how to do this in Debian-based Linux systems, but I have no experience with NAS systems. Sorry.

**Comment by wzh1895** [comment]
Thank you for your reply all the same! I have tried other non-nginx solutions and found a workaround.
Have a great day!
